// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CineTPI.Domain.Models;

public partial class Barrio
{
    [Key]
    [Column("id_pelicula")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdBarrio { get; set; }

    public string Barrio1 { get; set; }

    public int IdCiudad { get; set; }

    public virtual ICollection<Direccione> Direcciones { get; set; } = new List<Direccione>();

    public virtual Ciudade IdCiudadNavigation { get; set; }
}