// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPI.Domain.Models;

public partial class Butaca
{
    public int IdButaca { get; set; }

    public int IdTipoButacas { get; set; }

    public int IdEstadoButaca { get; set; }

    public int IdSala { get; set; }

    public string Fila { get; set; }

    public int Numero { get; set; }

    public virtual ICollection<Entrada> Entrada { get; set; } = new List<Entrada>();

    public virtual EstadosButaca IdEstadoButacaNavigation { get; set; }

    public virtual Sala IdSalaNavigation { get; set; }

    public virtual TiposButaca IdTipoButacasNavigation { get; set; }

    public virtual ICollection<ReservaDetalle> ReservaDetalles { get; set; } = new List<ReservaDetalle>();
}