// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CineTPI.Domain.Models;

public partial class Cajero
{
    [Key]
    [Column("id_pelicula")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdCajero { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public int IdTurno { get; set; }

    public int? IdSucursal { get; set; }

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();

    public virtual Sucursale IdSucursalNavigation { get; set; }

    public virtual Turno IdTurnoNavigation { get; set; }
}