// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPI.Domain.Models;

public partial class CanalesVenta
{
    public int IdCanalVenta { get; set; }

    public string CanalVenta { get; set; }

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();

    public virtual ICollection<Promocione> Promociones { get; set; } = new List<Promocione>();
}