// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CineTPI.Domain.Models;

public partial class CanalesVenta
{
    [Key]
    [Column("id_canal_venta")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdCanalVenta { get; set; }

    public string CanalVenta { get; set; }

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();

    public virtual ICollection<Promocione> Promociones { get; set; } = new List<Promocione>();
}