// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CineTPI.Domain.Models;

public partial class CineDBContext : DbContext
{
    public CineDBContext(DbContextOptions<CineDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Actore> Actores { get; set; }

    public virtual DbSet<Barrio> Barrios { get; set; }

    public virtual DbSet<Butaca> Butacas { get; set; }

    public virtual DbSet<Cajero> Cajeros { get; set; }

    public virtual DbSet<CanalesVenta> CanalesVentas { get; set; }

    public virtual DbSet<Ciudade> Ciudades { get; set; }

    public virtual DbSet<Clasificacione> Clasificaciones { get; set; }

    public virtual DbSet<Cliente> Clientes { get; set; }

    public virtual DbSet<ClientesContacto> ClientesContactos { get; set; }

    public virtual DbSet<Combo> Combos { get; set; }

    public virtual DbSet<CondicionesIva> CondicionesIvas { get; set; }

    public virtual DbSet<Contacto> Contactos { get; set; }

    public virtual DbSet<DetalleFactura> DetalleFacturas { get; set; }

    public virtual DbSet<DiasPromocione> DiasPromociones { get; set; }

    public virtual DbSet<Direccione> Direcciones { get; set; }

    public virtual DbSet<Directore> Directores { get; set; }

    public virtual DbSet<Distribuidore> Distribuidores { get; set; }

    public virtual DbSet<Entrada> Entradas { get; set; }

    public virtual DbSet<EstadosButaca> EstadosButacas { get; set; }

    public virtual DbSet<EstadosCompra> EstadosCompras { get; set; }

    public virtual DbSet<EstadosPromocione> EstadosPromociones { get; set; }

    public virtual DbSet<EstadosReserva> EstadosReservas { get; set; }

    public virtual DbSet<Factura> Facturas { get; set; }

    public virtual DbSet<FacturasFormasPago> FacturasFormasPagos { get; set; }

    public virtual DbSet<Financiera> Financieras { get; set; }

    public virtual DbSet<FormasPago> FormasPagos { get; set; }

    public virtual DbSet<FormatosPelicula> FormatosPeliculas { get; set; }

    public virtual DbSet<Funcion> Funciones { get; set; }

    public virtual DbSet<Genero> Generos { get; set; }

    public virtual DbSet<Horario> Horarios { get; set; }

    public virtual DbSet<Idioma> Idiomas { get; set; }

    public virtual DbSet<Marca> Marcas { get; set; }

    public virtual DbSet<Paise> Paises { get; set; }

    public virtual DbSet<Pelicula> Peliculas { get; set; }

    public virtual DbSet<PeliculasActore> PeliculasActores { get; set; }

    public virtual DbSet<PeliculasGenero> PeliculasGeneros { get; set; }

    public virtual DbSet<PeliculasIdioma> PeliculasIdiomas { get; set; }

    public virtual DbSet<PreferenciasCliente> PreferenciasClientes { get; set; }

    public virtual DbSet<ProductosCombo> ProductosCombos { get; set; }

    public virtual DbSet<ProductosShop> ProductosShops { get; set; }

    public virtual DbSet<Promocione> Promociones { get; set; }

    public virtual DbSet<PromocionesFuncione> PromocionesFunciones { get; set; }

    public virtual DbSet<PromocionesHorario> PromocionesHorarios { get; set; }

    public virtual DbSet<Provincia> Provincias { get; set; }

    public virtual DbSet<Puntuacione> Puntuaciones { get; set; }

    public virtual DbSet<ReseniasPelicula> ReseniasPeliculas { get; set; }

    public virtual DbSet<Reserva> Reservas { get; set; }

    public virtual DbSet<ReservaDetalle> ReservaDetalles { get; set; }

    public virtual DbSet<Sala> Salas { get; set; }

    public virtual DbSet<Sucursale> Sucursales { get; set; }

    public virtual DbSet<TiposButaca> TiposButacas { get; set; }

    public virtual DbSet<TiposCombo> TiposCombos { get; set; }

    public virtual DbSet<TiposContacto> TiposContactos { get; set; }

    public virtual DbSet<TiposDocumento> TiposDocumentos { get; set; }

    public virtual DbSet<TiposProducto> TiposProductos { get; set; }

    public virtual DbSet<TiposPromocione> TiposPromociones { get; set; }

    public virtual DbSet<TiposSala> TiposSalas { get; set; }

    public virtual DbSet<Turno> Turnos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Actore>(entity =>
        {
            entity.HasKey(e => e.IdActor).HasName("pk_actores");

            entity.ToTable("actores");

            entity.Property(e => e.IdActor)
                .ValueGeneratedNever()
                .HasColumnName("id_actor");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("apellido");
            entity.Property(e => e.Biografia)
                .HasMaxLength(2000)
                .IsUnicode(false)
                .HasColumnName("biografia");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");
        });

        modelBuilder.Entity<Barrio>(entity =>
        {
            entity.HasKey(e => e.IdBarrio).HasName("pk_barrio");

            entity.ToTable("barrios");

            entity.Property(e => e.IdBarrio)
                .ValueGeneratedNever()
                .HasColumnName("id_barrio");
            entity.Property(e => e.Barrio1)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("barrio");
            entity.Property(e => e.IdCiudad).HasColumnName("id_ciudad");

            entity.HasOne(d => d.IdCiudadNavigation).WithMany(p => p.Barrios)
                .HasForeignKey(d => d.IdCiudad)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_ciudad_barrio");
        });

        modelBuilder.Entity<Butaca>(entity =>
        {
            entity.HasKey(e => e.IdButaca).HasName("pk_butacas");

            entity.ToTable("butacas");

            entity.HasIndex(e => new { e.IdSala, e.Fila, e.Numero }, "idx_butaca_ubicacion").IsUnique();

            entity.Property(e => e.IdButaca)
                .ValueGeneratedNever()
                .HasColumnName("id_butaca");
            entity.Property(e => e.Fila)
                .IsRequired()
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasColumnName("fila");
            entity.Property(e => e.IdEstadoButaca).HasColumnName("id_estado_butaca");
            entity.Property(e => e.IdSala).HasColumnName("id_sala");
            entity.Property(e => e.IdTipoButacas).HasColumnName("id_tipo_butacas");
            entity.Property(e => e.Numero).HasColumnName("numero");

            entity.HasOne(d => d.IdEstadoButacaNavigation).WithMany(p => p.Butacas)
                .HasForeignKey(d => d.IdEstadoButaca)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_butacas_tipos_estados_butacas");

            entity.HasOne(d => d.IdSalaNavigation).WithMany(p => p.Butacas)
                .HasForeignKey(d => d.IdSala)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_butacas_salas");

            entity.HasOne(d => d.IdTipoButacasNavigation).WithMany(p => p.Butacas)
                .HasForeignKey(d => d.IdTipoButacas)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_butacas_tipos_butacas");
        });

        modelBuilder.Entity<Cajero>(entity =>
        {
            entity.HasKey(e => e.IdCajero).HasName("pk_cajeros");

            entity.ToTable("cajeros");

            entity.Property(e => e.IdCajero)
                .ValueGeneratedNever()
                .HasColumnName("id_cajero");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("apellido");
            entity.Property(e => e.IdSucursal).HasColumnName("id_sucursal");
            entity.Property(e => e.IdTurno).HasColumnName("id_turno");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");

            entity.HasOne(d => d.IdSucursalNavigation).WithMany(p => p.Cajeros)
                .HasForeignKey(d => d.IdSucursal)
                .HasConstraintName("fk_cajeros_sucursales");

            entity.HasOne(d => d.IdTurnoNavigation).WithMany(p => p.Cajeros)
                .HasForeignKey(d => d.IdTurno)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_cajeros_turnos");
        });

        modelBuilder.Entity<CanalesVenta>(entity =>
        {
            entity.HasKey(e => e.IdCanalVenta).HasName("pk_canales_ventas");

            entity.ToTable("canales_ventas");

            entity.Property(e => e.IdCanalVenta)
                .ValueGeneratedNever()
                .HasColumnName("id_canal_venta");
            entity.Property(e => e.CanalVenta)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("canal_venta");
        });

        modelBuilder.Entity<Ciudade>(entity =>
        {
            entity.HasKey(e => e.IdCiudad).HasName("pk_ciudad");

            entity.ToTable("ciudades");

            entity.Property(e => e.IdCiudad)
                .ValueGeneratedNever()
                .HasColumnName("id_ciudad");
            entity.Property(e => e.Ciudad)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("ciudad");
            entity.Property(e => e.IdProvincia).HasColumnName("id_provincia");

            entity.HasOne(d => d.IdProvinciaNavigation).WithMany(p => p.Ciudades)
                .HasForeignKey(d => d.IdProvincia)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_ciudad_provincia");
        });

        modelBuilder.Entity<Clasificacione>(entity =>
        {
            entity.HasKey(e => e.IdClasificacion).HasName("pk_clasificaciones");

            entity.ToTable("clasificaciones");

            entity.Property(e => e.IdClasificacion)
                .ValueGeneratedNever()
                .HasColumnName("id_clasificacion");
            entity.Property(e => e.Clasificacion)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("clasificacion");
        });

        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.CodCliente).HasName("pk_cliente");

            entity.ToTable("clientes");

            entity.Property(e => e.CodCliente)
                .ValueGeneratedNever()
                .HasColumnName("cod_cliente");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("apellido");
            entity.Property(e => e.EsAdmin).HasColumnName("es_admin");
            entity.Property(e => e.FechaNacimiento).HasColumnName("fecha_nacimiento");
            entity.Property(e => e.FechaRegistro)
                .HasColumnType("datetime")
                .HasColumnName("fecha_registro");
            entity.Property(e => e.IdDireccion).HasColumnName("id_direccion");
            entity.Property(e => e.IdTipoDoc).HasColumnName("id_tipo_doc");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");
            entity.Property(e => e.NroDoc)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("nro_doc");
            entity.Property(e => e.PasswordHash)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("password_hash");

            entity.HasOne(d => d.IdDireccionNavigation).WithMany(p => p.Clientes)
                .HasForeignKey(d => d.IdDireccion)
                .HasConstraintName("fk_clientes_direcciones");

            entity.HasOne(d => d.IdTipoDocNavigation).WithMany(p => p.Clientes)
                .HasForeignKey(d => d.IdTipoDoc)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_cliente_tipos_doc");
        });

        modelBuilder.Entity<ClientesContacto>(entity =>
        {
            entity.HasKey(e => e.IdClientesContacto).HasName("pk_clientes_contactos");

            entity.ToTable("clientes_contactos");

            entity.Property(e => e.IdClientesContacto)
                .ValueGeneratedNever()
                .HasColumnName("id_clientes_contacto");
            entity.Property(e => e.CodCliente).HasColumnName("cod_cliente");
            entity.Property(e => e.IdContacto).HasColumnName("id_contacto");

            entity.HasOne(d => d.CodClienteNavigation).WithMany(p => p.ClientesContactos)
                .HasForeignKey(d => d.CodCliente)
                .HasConstraintName("fk_clientes_contactos_clientes");

            entity.HasOne(d => d.IdContactoNavigation).WithMany(p => p.ClientesContactos)
                .HasForeignKey(d => d.IdContacto)
                .HasConstraintName("fk_clientes_contactos_contactos");
        });

        modelBuilder.Entity<Combo>(entity =>
        {
            entity.HasKey(e => e.IdCombo).HasName("pk_combos");

            entity.ToTable("combos");

            entity.Property(e => e.IdCombo)
                .ValueGeneratedNever()
                .HasColumnName("id_combo");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("descripcion");
            entity.Property(e => e.IdTipoCombo).HasColumnName("id_tipo_combo");

            entity.HasOne(d => d.IdTipoComboNavigation).WithMany(p => p.Combos)
                .HasForeignKey(d => d.IdTipoCombo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_combos_tipos_combos");
        });

        modelBuilder.Entity<CondicionesIva>(entity =>
        {
            entity.HasKey(e => e.IdCondicionIva).HasName("pk_condiciones_IVA");

            entity.ToTable("condiciones_IVA");

            entity.Property(e => e.IdCondicionIva)
                .ValueGeneratedNever()
                .HasColumnName("id_condicion_IVA");
            entity.Property(e => e.Condicion)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("condicion");
        });

        modelBuilder.Entity<Contacto>(entity =>
        {
            entity.HasKey(e => e.IdContacto).HasName("pk_contactos");

            entity.ToTable("contactos");

            entity.Property(e => e.IdContacto)
                .ValueGeneratedNever()
                .HasColumnName("id_contacto");
            entity.Property(e => e.Contacto1)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("contacto");
            entity.Property(e => e.IdTipoContacto).HasColumnName("id_tipo_contacto");

            entity.HasOne(d => d.IdTipoContactoNavigation).WithMany(p => p.Contactos)
                .HasForeignKey(d => d.IdTipoContacto)
                .HasConstraintName("fk_contactos_tipos");
        });

        modelBuilder.Entity<DetalleFactura>(entity =>
        {
            entity.HasKey(e => e.IdDetalleFactura).HasName("PK__detalle___F6BFE343714E9443");

            entity.ToTable("detalle_facturas");

            entity.Property(e => e.IdDetalleFactura).HasColumnName("id_detalle_factura");
            entity.Property(e => e.Cantidad)
                .HasDefaultValue(1)
                .HasColumnName("cantidad");
            entity.Property(e => e.IdProductoShop).HasColumnName("id_producto_shop");
            entity.Property(e => e.IdPromocion).HasColumnName("id_promocion");
            entity.Property(e => e.NroEntrada).HasColumnName("nro_entrada");
            entity.Property(e => e.NroFactura).HasColumnName("nro_factura");
            entity.Property(e => e.PrecioUnitario)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("precio_unitario");
            entity.Property(e => e.Subtotal)
                .HasComputedColumnSql("([cantidad]*[precio_unitario])", true)
                .HasColumnType("decimal(21, 2)")
                .HasColumnName("subtotal");

            entity.HasOne(d => d.IdProductoShopNavigation).WithMany(p => p.DetalleFacturas)
                .HasForeignKey(d => d.IdProductoShop)
                .HasConstraintName("FK__detalle_f__id_pr__756D6ECB");

            entity.HasOne(d => d.IdPromocionNavigation).WithMany(p => p.DetalleFacturas)
                .HasForeignKey(d => d.IdPromocion)
                .HasConstraintName("FK__detalle_f__id_pr__76619304");

            entity.HasOne(d => d.NroEntradaNavigation).WithMany(p => p.DetalleFacturas)
                .HasForeignKey(d => d.NroEntrada)
                .HasConstraintName("FK__detalle_f__nro_e__74794A92");

            entity.HasOne(d => d.NroFacturaNavigation).WithMany(p => p.DetalleFacturas)
                .HasForeignKey(d => d.NroFactura)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__detalle_f__nro_f__73852659");
        });

        modelBuilder.Entity<DiasPromocione>(entity =>
        {
            entity.HasKey(e => e.IdDiaPromocion).HasName("pk_dias_promociones");

            entity.ToTable("dias_promociones");

            entity.Property(e => e.IdDiaPromocion)
                .ValueGeneratedNever()
                .HasColumnName("id_dia_promocion");
            entity.Property(e => e.DiasPromocion)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("dias_promocion");
        });

        modelBuilder.Entity<Direccione>(entity =>
        {
            entity.HasKey(e => e.IdDireccion).HasName("pk_direccion");

            entity.ToTable("direcciones");

            entity.Property(e => e.IdDireccion)
                .ValueGeneratedNever()
                .HasColumnName("id_direccion");
            entity.Property(e => e.Altura).HasColumnName("altura");
            entity.Property(e => e.Calle)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("calle");
            entity.Property(e => e.Depto)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("depto");
            entity.Property(e => e.IdBarrio).HasColumnName("id_barrio");
            entity.Property(e => e.Piso).HasColumnName("piso");

            entity.HasOne(d => d.IdBarrioNavigation).WithMany(p => p.Direcciones)
                .HasForeignKey(d => d.IdBarrio)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_direcciones_barrios");
        });

        modelBuilder.Entity<Directore>(entity =>
        {
            entity.HasKey(e => e.IdDirector).HasName("PK__director__6B65E2A2570B728E");

            entity.ToTable("directores");

            entity.Property(e => e.IdDirector).HasColumnName("id_director");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("apellido");
            entity.Property(e => e.Bio)
                .HasMaxLength(2000)
                .IsUnicode(false)
                .HasColumnName("bio");
            entity.Property(e => e.FechaNacimiento).HasColumnName("fecha_nacimiento");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nombre");
        });

        modelBuilder.Entity<Distribuidore>(entity =>
        {
            entity.HasKey(e => e.IdDistribuidor).HasName("pk_distribuidores");

            entity.ToTable("distribuidores");

            entity.Property(e => e.IdDistribuidor)
                .ValueGeneratedNever()
                .HasColumnName("id_distribuidor");
            entity.Property(e => e.Distribuidor)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("distribuidor");
        });

        modelBuilder.Entity<Entrada>(entity =>
        {
            entity.HasKey(e => e.NroEntrada).HasName("PK__entradas__C52202D25313D3FA");

            entity.ToTable("entradas");

            entity.Property(e => e.NroEntrada)
                .ValueGeneratedNever()
                .HasColumnName("nro_entrada");
            entity.Property(e => e.IdButaca).HasColumnName("id_butaca");
            entity.Property(e => e.IdFuncion).HasColumnName("id_funcion");
            entity.Property(e => e.Precio)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("precio");
            entity.Property(e => e.PrecioUnitario)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("precio_unitario");

            entity.HasOne(d => d.IdButacaNavigation).WithMany(p => p.Entrada)
                .HasForeignKey(d => d.IdButaca)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_entradas_butaca");

            entity.HasOne(d => d.IdFuncionNavigation).WithMany(p => p.Entrada)
                .HasForeignKey(d => d.IdFuncion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_entradas_funcion");
        });

        modelBuilder.Entity<EstadosButaca>(entity =>
        {
            entity.HasKey(e => e.IdEstadoButaca).HasName("pk_estados_butacas");

            entity.ToTable("estados_butacas");

            entity.Property(e => e.IdEstadoButaca)
                .ValueGeneratedNever()
                .HasColumnName("id_estado_butaca");
            entity.Property(e => e.EstadoButaca)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("estado_butaca");
        });

        modelBuilder.Entity<EstadosCompra>(entity =>
        {
            entity.HasKey(e => e.IdEstadoCompra).HasName("pk_estados_compras");

            entity.ToTable("estados_compras");

            entity.Property(e => e.IdEstadoCompra)
                .ValueGeneratedNever()
                .HasColumnName("id_estado_compra");
            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("estado");
        });

        modelBuilder.Entity<EstadosPromocione>(entity =>
        {
            entity.HasKey(e => e.IdEstadoPromocion).HasName("pk_estados_promociones");

            entity.ToTable("estados_promociones");

            entity.Property(e => e.IdEstadoPromocion)
                .ValueGeneratedNever()
                .HasColumnName("id_estado_promocion");
            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("estado");
        });

        modelBuilder.Entity<EstadosReserva>(entity =>
        {
            entity.HasKey(e => e.IdEstadoReserva).HasName("pk_estados_reservas");

            entity.ToTable("estados_reservas");

            entity.Property(e => e.IdEstadoReserva)
                .ValueGeneratedNever()
                .HasColumnName("id_estado_reserva");
            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("estado");
        });

        modelBuilder.Entity<Factura>(entity =>
        {
            entity.HasKey(e => e.NroFactura).HasName("pk_factura");

            entity.ToTable("facturas");

            entity.Property(e => e.NroFactura)
                .ValueGeneratedNever()
                .HasColumnName("nro_factura");
            entity.Property(e => e.CodCliente).HasColumnName("cod_cliente");
            entity.Property(e => e.Fecha)
                .HasColumnType("datetime")
                .HasColumnName("fecha");
            entity.Property(e => e.IdCajero).HasColumnName("id_cajero");
            entity.Property(e => e.IdCanalVenta).HasColumnName("id_canal_venta");
            entity.Property(e => e.IdCondicionIva).HasColumnName("id_condicion_IVA");
            entity.Property(e => e.IdEstadoCompra).HasColumnName("id_estado_compra");
            entity.Property(e => e.IdFinanciera).HasColumnName("id_financiera");
            entity.Property(e => e.IdSucursal).HasColumnName("id_sucursal");

            entity.HasOne(d => d.CodClienteNavigation).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.CodCliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_facturas_clientes");

            entity.HasOne(d => d.IdCajeroNavigation).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.IdCajero)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_facturas_cajeros");

            entity.HasOne(d => d.IdCanalVentaNavigation).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.IdCanalVenta)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_facturas_canales_ventas");

            entity.HasOne(d => d.IdCondicionIvaNavigation).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.IdCondicionIva)
                .HasConstraintName("fk_facturas_condiciones_IVA");

            entity.HasOne(d => d.IdEstadoCompraNavigation).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.IdEstadoCompra)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_facturas_estados_compras");

            entity.HasOne(d => d.IdFinancieraNavigation).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.IdFinanciera)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_facturas_financieras");

            entity.HasOne(d => d.IdSucursalNavigation).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.IdSucursal)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_facturas_sucursales");
        });

        modelBuilder.Entity<FacturasFormasPago>(entity =>
        {
            entity.HasKey(e => e.IdFacturaFormaPago).HasName("pk_facturas_formas_pagos");

            entity.ToTable("facturas_formas_pagos");

            entity.Property(e => e.IdFacturaFormaPago)
                .ValueGeneratedNever()
                .HasColumnName("id_factura_forma_pago");
            entity.Property(e => e.IdFormaPago).HasColumnName("id_forma_pago");
            entity.Property(e => e.NroFactura).HasColumnName("nro_factura");

            entity.HasOne(d => d.IdFormaPagoNavigation).WithMany(p => p.FacturasFormasPagos)
                .HasForeignKey(d => d.IdFormaPago)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_facturas_formas_pagos_formas_pagos");

            entity.HasOne(d => d.NroFacturaNavigation).WithMany(p => p.FacturasFormasPagos)
                .HasForeignKey(d => d.NroFactura)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_facturas_formas_pagos_facturas");
        });

        modelBuilder.Entity<Financiera>(entity =>
        {
            entity.HasKey(e => e.IdFinanciera).HasName("pk_financieras");

            entity.ToTable("financieras");

            entity.Property(e => e.IdFinanciera)
                .ValueGeneratedNever()
                .HasColumnName("id_financiera");
            entity.Property(e => e.Financiera1)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("financiera");
        });

        modelBuilder.Entity<FormasPago>(entity =>
        {
            entity.HasKey(e => e.IdFormaPago).HasName("pk_forma_pago");

            entity.ToTable("formas_pagos");

            entity.Property(e => e.IdFormaPago)
                .ValueGeneratedNever()
                .HasColumnName("id_forma_pago");
            entity.Property(e => e.FormaPago)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("forma_pago");
        });

        modelBuilder.Entity<FormatosPelicula>(entity =>
        {
            entity.HasKey(e => e.IdFormatoPelicula).HasName("pk_formatos_peliculas");

            entity.ToTable("formatos_peliculas");

            entity.Property(e => e.IdFormatoPelicula)
                .ValueGeneratedNever()
                .HasColumnName("id_formato_pelicula");
            entity.Property(e => e.Formato)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("formato");
        });

        modelBuilder.Entity<Funcion>(entity =>
        {
            entity.HasKey(e => e.IdFuncion).HasName("PK__funcione__F6DE6FC96B3F6159");

            entity.ToTable("funciones");

            entity.Property(e => e.IdFuncion)
                .ValueGeneratedNever()
                .HasColumnName("id_funcion");
            entity.Property(e => e.Fecha).HasColumnName("fecha");
            entity.Property(e => e.IdHorario).HasColumnName("id_horario");
            entity.Property(e => e.IdPelicula).HasColumnName("id_pelicula");
            entity.Property(e => e.IdSala).HasColumnName("id_sala");

            entity.HasOne(d => d.IdHorarioNavigation).WithMany(p => p.Funciones)
                .HasForeignKey(d => d.IdHorario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_funciones_horario");

            entity.HasOne(d => d.IdPeliculaNavigation).WithMany(p => p.Funciones)
                .HasForeignKey(d => d.IdPelicula)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_funciones_pelicula");

            entity.HasOne(d => d.IdSalaNavigation).WithMany(p => p.Funciones)
                .HasForeignKey(d => d.IdSala)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_funciones_sala");
        });

        modelBuilder.Entity<Genero>(entity =>
        {
            entity.HasKey(e => e.IdGenero).HasName("pk_generos");

            entity.ToTable("generos");

            entity.Property(e => e.IdGenero)
                .ValueGeneratedNever()
                .HasColumnName("id_genero");
            entity.Property(e => e.Genero1)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("genero");
        });

        modelBuilder.Entity<Horario>(entity =>
        {
            entity.HasKey(e => e.IdHorario).HasName("pk_horarios");

            entity.ToTable("horarios");

            entity.Property(e => e.IdHorario)
                .ValueGeneratedNever()
                .HasColumnName("id_horario");
            entity.Property(e => e.Horario1).HasColumnName("horario");
        });

        modelBuilder.Entity<Idioma>(entity =>
        {
            entity.HasKey(e => e.IdIdioma).HasName("pk_idioma");

            entity.ToTable("idiomas");

            entity.Property(e => e.IdIdioma)
                .ValueGeneratedNever()
                .HasColumnName("id_idioma");
            entity.Property(e => e.Idioma1)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("idioma");
        });

        modelBuilder.Entity<Marca>(entity =>
        {
            entity.HasKey(e => e.IdMarca).HasName("pk_marcas");

            entity.ToTable("marcas");

            entity.Property(e => e.IdMarca)
                .ValueGeneratedNever()
                .HasColumnName("id_marca");
            entity.Property(e => e.Marca1)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("marca");
        });

        modelBuilder.Entity<Paise>(entity =>
        {
            entity.HasKey(e => e.IdPais).HasName("pk_pais");

            entity.ToTable("paises");

            entity.Property(e => e.IdPais)
                .ValueGeneratedNever()
                .HasColumnName("id_pais");
            entity.Property(e => e.Pais)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("pais");
        });

        modelBuilder.Entity<Pelicula>(entity =>
        {
            entity.HasKey(e => e.IdPelicula).HasName("pk_pelicula");

            entity.ToTable("peliculas");

            entity.Property(e => e.IdPelicula)
                .ValueGeneratedNever()
                .HasColumnName("id_pelicula");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(2000)
                .IsUnicode(false)
                .HasColumnName("descripcion");
            entity.Property(e => e.FechaLanzamiento).HasColumnName("fecha_lanzamiento");
            entity.Property(e => e.IdClasificacion).HasColumnName("id_clasificacion");
            entity.Property(e => e.IdDirector).HasColumnName("id_director");
            entity.Property(e => e.IdDistribuidor).HasColumnName("id_distribuidor");
            entity.Property(e => e.IdFormatoPelicula).HasColumnName("id_formato_pelicula");
            entity.Property(e => e.IdPais).HasColumnName("id_pais");
            entity.Property(e => e.Titulo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("titulo");

            entity.HasOne(d => d.IdClasificacionNavigation).WithMany(p => p.Peliculas)
                .HasForeignKey(d => d.IdClasificacion)
                .HasConstraintName("fk_peliculas_clasificaciones");

            entity.HasOne(d => d.IdDirectorNavigation).WithMany(p => p.Peliculas)
                .HasForeignKey(d => d.IdDirector)
                .HasConstraintName("fk_peliculas_director");

            entity.HasOne(d => d.IdDistribuidorNavigation).WithMany(p => p.Peliculas)
                .HasForeignKey(d => d.IdDistribuidor)
                .HasConstraintName("fk_peliculas_distribuidores");

            entity.HasOne(d => d.IdFormatoPeliculaNavigation).WithMany(p => p.Peliculas)
                .HasForeignKey(d => d.IdFormatoPelicula)
                .HasConstraintName("fk_peliculas_formatos_peliculas");

            entity.HasOne(d => d.IdPaisNavigation).WithMany(p => p.Peliculas)
                .HasForeignKey(d => d.IdPais)
                .HasConstraintName("fk_peliculas_paises");
        });

        modelBuilder.Entity<PeliculasActore>(entity =>
        {
            entity.HasKey(e => e.IdPeliculaActor).HasName("pk_peliculas_actores");

            entity.ToTable("peliculas_actores");

            entity.Property(e => e.IdPeliculaActor)
                .ValueGeneratedNever()
                .HasColumnName("id_pelicula_actor");
            entity.Property(e => e.IdActor).HasColumnName("id_actor");
            entity.Property(e => e.IdPelicula).HasColumnName("id_pelicula");

            entity.HasOne(d => d.IdActorNavigation).WithMany(p => p.PeliculasActores)
                .HasForeignKey(d => d.IdActor)
                .HasConstraintName("fk_peliculas_actores");

            entity.HasOne(d => d.IdPeliculaNavigation).WithMany(p => p.PeliculasActores)
                .HasForeignKey(d => d.IdPelicula)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_peliculas_actores_peliculas");
        });

        modelBuilder.Entity<PeliculasGenero>(entity =>
        {
            entity.HasKey(e => e.IdPeliculaGenero).HasName("pk_peliculas_generos");

            entity.ToTable("peliculas_generos");

            entity.Property(e => e.IdPeliculaGenero)
                .ValueGeneratedNever()
                .HasColumnName("id_pelicula_genero");
            entity.Property(e => e.IdGenero).HasColumnName("id_genero");
            entity.Property(e => e.IdPelicula).HasColumnName("id_pelicula");

            entity.HasOne(d => d.IdGeneroNavigation).WithMany(p => p.PeliculasGeneros)
                .HasForeignKey(d => d.IdGenero)
                .HasConstraintName("fk_peliculas_generos_generos");

            entity.HasOne(d => d.IdPeliculaNavigation).WithMany(p => p.PeliculasGeneros)
                .HasForeignKey(d => d.IdPelicula)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_peliculas_generos_peliculas");
        });

        modelBuilder.Entity<PeliculasIdioma>(entity =>
        {
            entity.HasKey(e => e.IdPeliculaIdioma).HasName("pk_peliculas_idiomas");

            entity.ToTable("peliculas_idiomas");

            entity.Property(e => e.IdPeliculaIdioma)
                .ValueGeneratedNever()
                .HasColumnName("id_pelicula_idioma");
            entity.Property(e => e.IdIdioma).HasColumnName("id_idioma");
            entity.Property(e => e.IdPelicula).HasColumnName("id_pelicula");

            entity.HasOne(d => d.IdIdiomaNavigation).WithMany(p => p.PeliculasIdiomas)
                .HasForeignKey(d => d.IdIdioma)
                .HasConstraintName("fk_peliculas_idiomas_idiomas");

            entity.HasOne(d => d.IdPeliculaNavigation).WithMany(p => p.PeliculasIdiomas)
                .HasForeignKey(d => d.IdPelicula)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_peliculas_idiomas_peliculas");
        });

        modelBuilder.Entity<PreferenciasCliente>(entity =>
        {
            entity.HasKey(e => e.IdPreferenciaCliente).HasName("pk_preferencia_cliente");

            entity.ToTable("preferencias_clientes");

            entity.Property(e => e.IdPreferenciaCliente)
                .ValueGeneratedNever()
                .HasColumnName("id_preferencia_cliente");
            entity.Property(e => e.CodCliente).HasColumnName("cod_cliente");
            entity.Property(e => e.IdGenero).HasColumnName("id_genero");
            entity.Property(e => e.SuscribeNewsletter)
                .HasDefaultValue(false)
                .HasColumnName("suscribe_newsletter");

            entity.HasOne(d => d.CodClienteNavigation).WithMany(p => p.PreferenciasClientes)
                .HasForeignKey(d => d.CodCliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_preferencias_clientes_clientes");

            entity.HasOne(d => d.IdGeneroNavigation).WithMany(p => p.PreferenciasClientes)
                .HasForeignKey(d => d.IdGenero)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_preferencias_clientes_generos");
        });

        modelBuilder.Entity<ProductosCombo>(entity =>
        {
            entity.HasKey(e => e.IdProductoCombo).HasName("pk_productos_combos");

            entity.ToTable("productos_combos");

            entity.Property(e => e.IdProductoCombo)
                .ValueGeneratedNever()
                .HasColumnName("id_producto_combo");
            entity.Property(e => e.IdCombo).HasColumnName("id_combo");
            entity.Property(e => e.IdProductoShop).HasColumnName("id_producto_shop");
            entity.Property(e => e.PrecioUnitario)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("precio_unitario");

            entity.HasOne(d => d.IdComboNavigation).WithMany(p => p.ProductosCombos)
                .HasForeignKey(d => d.IdCombo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_productos_combos_combos");

            entity.HasOne(d => d.IdProductoShopNavigation).WithMany(p => p.ProductosCombos)
                .HasForeignKey(d => d.IdProductoShop)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_productos_combos_productos");
        });

        modelBuilder.Entity<ProductosShop>(entity =>
        {
            entity.HasKey(e => e.IdProductoShop).HasName("pk_productos_shop");

            entity.ToTable("productos_shop");

            entity.Property(e => e.IdProductoShop)
                .ValueGeneratedNever()
                .HasColumnName("id_producto_shop");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("descripcion");
            entity.Property(e => e.IdMarca).HasColumnName("id_marca");
            entity.Property(e => e.IdTipoProducto).HasColumnName("id_tipo_producto");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");
            entity.Property(e => e.Precio)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("precio");
            entity.Property(e => e.Stock).HasColumnName("stock");

            entity.HasOne(d => d.IdMarcaNavigation).WithMany(p => p.ProductosShops)
                .HasForeignKey(d => d.IdMarca)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_productos_shop_marcas");

            entity.HasOne(d => d.IdTipoProductoNavigation).WithMany(p => p.ProductosShops)
                .HasForeignKey(d => d.IdTipoProducto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_productos_shop_tipos_productos");
        });

        modelBuilder.Entity<Promocione>(entity =>
        {
            entity.HasKey(e => e.IdPromocion).HasName("pk_promociones");

            entity.ToTable("promociones");

            entity.Property(e => e.IdPromocion)
                .ValueGeneratedNever()
                .HasColumnName("id_promocion");
            entity.Property(e => e.CodCliente).HasColumnName("cod_cliente");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("descripcion");
            entity.Property(e => e.IdCanalVenta).HasColumnName("id_canal_venta");
            entity.Property(e => e.IdDiaPromocion).HasColumnName("id_dia_promocion");
            entity.Property(e => e.IdEstadoPromocion).HasColumnName("id_estado_promocion");
            entity.Property(e => e.IdFinanciera).HasColumnName("id_financiera");
            entity.Property(e => e.IdTipoPromocion).HasColumnName("id_tipo_promocion");

            entity.HasOne(d => d.CodClienteNavigation).WithMany(p => p.Promociones)
                .HasForeignKey(d => d.CodCliente)
                .HasConstraintName("fk_promociones_clientes");

            entity.HasOne(d => d.IdCanalVentaNavigation).WithMany(p => p.Promociones)
                .HasForeignKey(d => d.IdCanalVenta)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_promociones_canales_ventas");

            entity.HasOne(d => d.IdDiaPromocionNavigation).WithMany(p => p.Promociones)
                .HasForeignKey(d => d.IdDiaPromocion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_promociones_dias_promociones");

            entity.HasOne(d => d.IdEstadoPromocionNavigation).WithMany(p => p.Promociones)
                .HasForeignKey(d => d.IdEstadoPromocion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_promociones_estados_promociones");

            entity.HasOne(d => d.IdFinancieraNavigation).WithMany(p => p.Promociones)
                .HasForeignKey(d => d.IdFinanciera)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_promociones_financieras");

            entity.HasOne(d => d.IdTipoPromocionNavigation).WithMany(p => p.Promociones)
                .HasForeignKey(d => d.IdTipoPromocion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_promociones_tipos_promociones");
        });

        modelBuilder.Entity<PromocionesFuncione>(entity =>
        {
            entity.HasKey(e => e.IdPromocionFuncion).HasName("PK__promocio__280615E3DBD1D40D");

            entity.ToTable("promociones_funciones");

            entity.Property(e => e.IdPromocionFuncion)
                .ValueGeneratedNever()
                .HasColumnName("id_promocion_funcion");
            entity.Property(e => e.IdFuncion).HasColumnName("id_funcion");
            entity.Property(e => e.IdPromocion).HasColumnName("id_promocion");

            entity.HasOne(d => d.IdFuncionNavigation).WithMany(p => p.PromocionesFunciones)
                .HasForeignKey(d => d.IdFuncion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_promociones_funciones_funciones");

            entity.HasOne(d => d.IdPromocionNavigation).WithMany(p => p.PromocionesFunciones)
                .HasForeignKey(d => d.IdPromocion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_promociones_funciones_promociones");
        });

        modelBuilder.Entity<PromocionesHorario>(entity =>
        {
            entity.HasKey(e => e.IdPromocionHorario).HasName("PK__promocio__8C8D21A101E4AB29");

            entity.ToTable("promociones_horarios");

            entity.Property(e => e.IdPromocionHorario)
                .ValueGeneratedNever()
                .HasColumnName("id_promocion_horario");
            entity.Property(e => e.IdHorario).HasColumnName("id_horario");
            entity.Property(e => e.IdPromocion).HasColumnName("id_promocion");

            entity.HasOne(d => d.IdHorarioNavigation).WithMany(p => p.PromocionesHorarios)
                .HasForeignKey(d => d.IdHorario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_promociones_horarios_horarios");

            entity.HasOne(d => d.IdPromocionNavigation).WithMany(p => p.PromocionesHorarios)
                .HasForeignKey(d => d.IdPromocion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_promociones_horarios_promociones");
        });

        modelBuilder.Entity<Provincia>(entity =>
        {
            entity.HasKey(e => e.IdProvincia).HasName("pk_provincia");

            entity.ToTable("provincias");

            entity.Property(e => e.IdProvincia)
                .ValueGeneratedNever()
                .HasColumnName("id_provincia");
            entity.Property(e => e.IdPais).HasColumnName("id_pais");
            entity.Property(e => e.Provincia1)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("provincia");

            entity.HasOne(d => d.IdPaisNavigation).WithMany(p => p.Provincia)
                .HasForeignKey(d => d.IdPais)
                .HasConstraintName("fk_provincias_pais");
        });

        modelBuilder.Entity<Puntuacione>(entity =>
        {
            entity.HasKey(e => e.IdPuntuacion).HasName("pk_puntuacion");

            entity.ToTable("puntuaciones");

            entity.Property(e => e.IdPuntuacion)
                .ValueGeneratedNever()
                .HasColumnName("id_puntuacion");
            entity.Property(e => e.Puntuacion).HasColumnName("puntuacion");
        });

        modelBuilder.Entity<ReseniasPelicula>(entity =>
        {
            entity.HasKey(e => e.IdResenia).HasName("pk_resenias");

            entity.ToTable("resenias_peliculas");

            entity.Property(e => e.IdResenia)
                .ValueGeneratedNever()
                .HasColumnName("id_resenia");
            entity.Property(e => e.CodCliente).HasColumnName("cod_cliente");
            entity.Property(e => e.Comentario)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false)
                .HasColumnName("comentario");
            entity.Property(e => e.FechaResenia)
                .HasColumnType("datetime")
                .HasColumnName("fecha_resenia");
            entity.Property(e => e.IdPelicula).HasColumnName("id_pelicula");
            entity.Property(e => e.IdPuntuacion).HasColumnName("id_puntuacion");

            entity.HasOne(d => d.CodClienteNavigation).WithMany(p => p.ReseniasPeliculas)
                .HasForeignKey(d => d.CodCliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_resenias_clientes");

            entity.HasOne(d => d.IdPeliculaNavigation).WithMany(p => p.ReseniasPeliculas)
                .HasForeignKey(d => d.IdPelicula)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_resenias_peliculas");

            entity.HasOne(d => d.IdPuntuacionNavigation).WithMany(p => p.ReseniasPeliculas)
                .HasForeignKey(d => d.IdPuntuacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_resenias_puntuaciones");
        });

        modelBuilder.Entity<Reserva>(entity =>
        {
            entity.HasKey(e => e.IdReserva).HasName("pk_reservas");

            entity.ToTable("reservas");

            entity.Property(e => e.IdReserva)
                .ValueGeneratedNever()
                .HasColumnName("id_reserva");
            entity.Property(e => e.CodCliente).HasColumnName("cod_cliente");
            entity.Property(e => e.Fecha).HasColumnName("fecha");
            entity.Property(e => e.IdEstadoReserva).HasColumnName("id_estado_reserva");
            entity.Property(e => e.MontoReserva)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("monto_reserva");

            entity.HasOne(d => d.CodClienteNavigation).WithMany(p => p.Reservas)
                .HasForeignKey(d => d.CodCliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_reservas_clientes");

            entity.HasOne(d => d.IdEstadoReservaNavigation).WithMany(p => p.Reservas)
                .HasForeignKey(d => d.IdEstadoReserva)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_reservas_estados_reservas");
        });

        modelBuilder.Entity<ReservaDetalle>(entity =>
        {
            entity.HasKey(e => e.IdReservaDetalle).HasName("PK__reserva___2205129AC5F2F901");

            entity.ToTable("reserva_detalle");

            entity.HasIndex(e => new { e.IdFuncion, e.IdButaca }, "uq_reserva_detalle_funcion_butaca").IsUnique();

            entity.Property(e => e.IdReservaDetalle).HasColumnName("id_reserva_detalle");
            entity.Property(e => e.IdButaca).HasColumnName("id_butaca");
            entity.Property(e => e.IdFuncion).HasColumnName("id_funcion");
            entity.Property(e => e.IdReserva).HasColumnName("id_reserva");

            entity.HasOne(d => d.IdButacaNavigation).WithMany(p => p.ReservaDetalles)
                .HasForeignKey(d => d.IdButaca)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_reserva_detalle_butaca");

            entity.HasOne(d => d.IdFuncionNavigation).WithMany(p => p.ReservaDetalles)
                .HasForeignKey(d => d.IdFuncion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_reserva_detalle_funcion");

            entity.HasOne(d => d.IdReservaNavigation).WithMany(p => p.ReservaDetalles)
                .HasForeignKey(d => d.IdReserva)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_reserva_detalle_reserva");
        });

        modelBuilder.Entity<Sala>(entity =>
        {
            entity.HasKey(e => e.IdSala).HasName("pk_salas");

            entity.ToTable("salas");

            entity.Property(e => e.IdSala)
                .ValueGeneratedNever()
                .HasColumnName("id_sala");
            entity.Property(e => e.IdSucursal).HasColumnName("id_sucursal");
            entity.Property(e => e.IdTipoSala).HasColumnName("id_tipo_sala");
            entity.Property(e => e.NroSala).HasColumnName("nro_sala");

            entity.HasOne(d => d.IdSucursalNavigation).WithMany(p => p.Salas)
                .HasForeignKey(d => d.IdSucursal)
                .HasConstraintName("fk_salas_sucursales");

            entity.HasOne(d => d.IdTipoSalaNavigation).WithMany(p => p.Salas)
                .HasForeignKey(d => d.IdTipoSala)
                .HasConstraintName("fk_salas_tipos_salas");
        });

        modelBuilder.Entity<Sucursale>(entity =>
        {
            entity.HasKey(e => e.IdSucursal).HasName("pk_sucursales");

            entity.ToTable("sucursales");

            entity.Property(e => e.IdSucursal)
                .ValueGeneratedNever()
                .HasColumnName("id_sucursal");
            entity.Property(e => e.IdDireccion).HasColumnName("id_direccion");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");

            entity.HasOne(d => d.IdDireccionNavigation).WithMany(p => p.Sucursales)
                .HasForeignKey(d => d.IdDireccion)
                .HasConstraintName("fk_sucursales_direcciones");
        });

        modelBuilder.Entity<TiposButaca>(entity =>
        {
            entity.HasKey(e => e.IdTipoButacas).HasName("pk_tipos_butacas");

            entity.ToTable("tipos_butacas");

            entity.Property(e => e.IdTipoButacas)
                .ValueGeneratedNever()
                .HasColumnName("id_tipo_butacas");
            entity.Property(e => e.TipoButaca)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("tipo_butaca");
        });

        modelBuilder.Entity<TiposCombo>(entity =>
        {
            entity.HasKey(e => e.IdTipoCombo).HasName("pk_tipos_combos");

            entity.ToTable("tipos_combos");

            entity.Property(e => e.IdTipoCombo)
                .ValueGeneratedNever()
                .HasColumnName("id_tipo_combo");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("descripcion");
        });

        modelBuilder.Entity<TiposContacto>(entity =>
        {
            entity.HasKey(e => e.IdTipoContacto).HasName("pk_tipo_contacto");

            entity.ToTable("tipos_contactos");

            entity.Property(e => e.IdTipoContacto)
                .ValueGeneratedNever()
                .HasColumnName("id_tipo_contacto");
            entity.Property(e => e.Tipo)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("tipo");
        });

        modelBuilder.Entity<TiposDocumento>(entity =>
        {
            entity.HasKey(e => e.IdTipoDoc).HasName("pk_tipo_doc");

            entity.ToTable("tipos_documentos");

            entity.Property(e => e.IdTipoDoc)
                .ValueGeneratedNever()
                .HasColumnName("id_tipo_doc");
            entity.Property(e => e.Tipo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("tipo");
        });

        modelBuilder.Entity<TiposProducto>(entity =>
        {
            entity.HasKey(e => e.IdTipoProducto).HasName("pk_tipos_productos");

            entity.ToTable("tipos_productos");

            entity.Property(e => e.IdTipoProducto)
                .ValueGeneratedNever()
                .HasColumnName("id_tipo_producto");
            entity.Property(e => e.TipoProducto)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("tipo_producto");
        });

        modelBuilder.Entity<TiposPromocione>(entity =>
        {
            entity.HasKey(e => e.IdTipoPromocion).HasName("pk_tipos_promociones");

            entity.ToTable("tipos_promociones");

            entity.Property(e => e.IdTipoPromocion)
                .ValueGeneratedNever()
                .HasColumnName("id_tipo_promocion");
            entity.Property(e => e.TipoPromocion)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("tipo_promocion");
        });

        modelBuilder.Entity<TiposSala>(entity =>
        {
            entity.HasKey(e => e.IdTipoSala).HasName("pk_tipos_salas");

            entity.ToTable("tipos_salas");

            entity.Property(e => e.IdTipoSala)
                .ValueGeneratedNever()
                .HasColumnName("id_tipo_sala");
            entity.Property(e => e.TipoSala)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("tipo_sala");
        });

        modelBuilder.Entity<Turno>(entity =>
        {
            entity.HasKey(e => e.IdTurno).HasName("pk_turnos");

            entity.ToTable("turnos");

            entity.Property(e => e.IdTurno)
                .ValueGeneratedNever()
                .HasColumnName("id_turno");
            entity.Property(e => e.Turno1)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("turno");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}