// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CineTPI.Domain.Models;

public partial class Clasificacione
{
    [Key]
    [Column("id_clasificacion")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdClasificacion { get; set; }

    public string Clasificacion { get; set; }

    public virtual ICollection<Pelicula> Peliculas { get; set; } = new List<Pelicula>();
}