// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CineTPI.Domain.Models;

public partial class ClientesContacto
{
    [Key]
    [Column("id_pelicula")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdClientesContacto { get; set; }

    public int? IdContacto { get; set; }

    public int? CodCliente { get; set; }

    public virtual Cliente CodClienteNavigation { get; set; }

    public virtual Contacto IdContactoNavigation { get; set; }
}