// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPI.Domain.Models;

public partial class ClientesContacto
{
    public int IdClientesContacto { get; set; }

    public int? IdContacto { get; set; }

    public int? CodCliente { get; set; }

    public virtual Cliente CodClienteNavigation { get; set; }

    public virtual Contacto IdContactoNavigation { get; set; }
}