// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CineTPI.Domain.Models;

public partial class Cliente
{
    [Key]
    [Column("id_pelicula")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int CodCliente { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string NroDoc { get; set; }

    public int IdTipoDoc { get; set; }

    public DateOnly? FechaNacimiento { get; set; }

    public DateTime FechaRegistro { get; set; }

    public int? IdDireccion { get; set; }

    public string PasswordHash { get; set; }

    public bool EsAdmin { get; set; }

    public virtual ICollection<ClientesContacto> ClientesContactos { get; set; } = new List<ClientesContacto>();

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();

    public virtual Direccione IdDireccionNavigation { get; set; }

    public virtual TiposDocumento IdTipoDocNavigation { get; set; }

    public virtual ICollection<PreferenciasCliente> PreferenciasClientes { get; set; } = new List<PreferenciasCliente>();

    public virtual ICollection<Promocione> Promociones { get; set; } = new List<Promocione>();

    public virtual ICollection<ReseniasPelicula> ReseniasPeliculas { get; set; } = new List<ReseniasPelicula>();

    public virtual ICollection<Reserva> Reservas { get; set; } = new List<Reserva>();
}