// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CineTPI.Domain.Models;

public partial class Combo
{
    [Key]
    [Column("id_combo")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdCombo { get; set; }

    public string Descripcion { get; set; }

    public int IdTipoCombo { get; set; }

    public virtual TiposCombo IdTipoComboNavigation { get; set; }

    public virtual ICollection<ProductosCombo> ProductosCombos { get; set; } = new List<ProductosCombo>();
}