// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CineTPI.Domain.Models;

public partial class CondicionesIva
{
    [Key]
    [Column("id_condicion_iva")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdCondicionIva { get; set; }

    public string Condicion { get; set; }

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();
}