// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPI.Domain.Models;

public partial class CondicionesIva
{
    public int IdCondicionIva { get; set; }

    public string Condicion { get; set; }

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();
}