// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CineTPI.Domain.Models;

public partial class DetalleFactura
{
    [Key]
    [Column("id_detalle_factura")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdDetalleFactura { get; set; }

    public int NroFactura { get; set; }

    public int? NroEntrada { get; set; }

    public int? IdProductoShop { get; set; }

    public int? IdPromocion { get; set; }

    public int Cantidad { get; set; }

    public decimal PrecioUnitario { get; set; }

    public decimal? Subtotal { get; set; }

    public virtual ProductosShop IdProductoShopNavigation { get; set; }

    public virtual Promocione IdPromocionNavigation { get; set; }

    public virtual Entrada NroEntradaNavigation { get; set; }

    public virtual Factura NroFacturaNavigation { get; set; }
}