// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPI.Domain.Models;

public partial class DiasPromocione
{
    public int IdDiaPromocion { get; set; }

    public string DiasPromocion { get; set; }

    public virtual ICollection<Promocione> Promociones { get; set; } = new List<Promocione>();
}