// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CineTPI.Domain.Models;

public partial class Entrada
{
    [Key]
    [Column("nro_entrada")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int NroEntrada { get; set; }

    public int IdFuncion { get; set; }

    public int IdButaca { get; set; }

    public decimal Precio { get; set; }

    public decimal PrecioUnitario { get; set; }

    public virtual ICollection<DetalleFactura> DetalleFacturas { get; set; } = new List<DetalleFactura>();

    public virtual Butaca IdButacaNavigation { get; set; }

    public virtual Funcion IdFuncionNavigation { get; set; }
}