// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPI.Domain.Models;

public partial class EstadosButaca
{
    public int IdEstadoButaca { get; set; }

    public string EstadoButaca { get; set; }

    public virtual ICollection<Butaca> Butacas { get; set; } = new List<Butaca>();
}