// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CineTPI.Domain.Models;

public partial class EstadosReserva
{
    [Key]
    [Column("id_estado_reserva")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdEstadoReserva { get; set; }

    public string Estado { get; set; }

    public virtual ICollection<Reserva> Reservas { get; set; } = new List<Reserva>();
}