// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPI.Domain.Models;

public partial class FacturasFormasPago
{
    public int IdFacturaFormaPago { get; set; }

    public int NroFactura { get; set; }

    public int IdFormaPago { get; set; }

    public virtual FormasPago IdFormaPagoNavigation { get; set; }

    public virtual Factura NroFacturaNavigation { get; set; }
}