// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CineTPI.Domain.Models;

public partial class FacturasFormasPago
{
    [Key]
    [Column("id_pelicula")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdFacturaFormaPago { get; set; }

    public int NroFactura { get; set; }

    public int IdFormaPago { get; set; }

    public virtual FormasPago IdFormaPagoNavigation { get; set; }

    public virtual Factura NroFacturaNavigation { get; set; }
}