// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CineTPI.Domain.Models;

public partial class Factura
{
    [Key]
    [Column("id_pelicula")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int NroFactura { get; set; }

    public int? IdCondicionIva { get; set; }

    public DateTime Fecha { get; set; }

    public int CodCliente { get; set; }

    public int IdCajero { get; set; }

    public int IdSucursal { get; set; }

    public int IdFinanciera { get; set; }

    public int IdEstadoCompra { get; set; }

    public int IdCanalVenta { get; set; }

    public virtual Cliente CodClienteNavigation { get; set; }

    public virtual ICollection<DetalleFactura> DetalleFacturas { get; set; } = new List<DetalleFactura>();

    public virtual ICollection<FacturasFormasPago> FacturasFormasPagos { get; set; } = new List<FacturasFormasPago>();

    public virtual Cajero IdCajeroNavigation { get; set; }

    public virtual CanalesVenta IdCanalVentaNavigation { get; set; }

    public virtual CondicionesIva IdCondicionIvaNavigation { get; set; }

    public virtual EstadosCompra IdEstadoCompraNavigation { get; set; }

    public virtual Financiera IdFinancieraNavigation { get; set; }

    public virtual Sucursale IdSucursalNavigation { get; set; }
}