// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CineTPI.Domain.Models;

public partial class Financiera
{
    [Key]
    [Column("id_financiera")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdFinanciera { get; set; }

    public string Financiera1 { get; set; }

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();

    public virtual ICollection<Promocione> Promociones { get; set; } = new List<Promocione>();
}