// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CineTPI.Domain.Models;

public partial class Genero
{
    [Key]
    [Column("id_genero")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdGenero { get; set; }

    public string Genero1 { get; set; }

    public virtual ICollection<PeliculasGenero> PeliculasGeneros { get; set; } = new List<PeliculasGenero>();

    public virtual ICollection<PreferenciasCliente> PreferenciasClientes { get; set; } = new List<PreferenciasCliente>();

}