// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPI.Domain.Models;

public partial class Horario
{
    public int IdHorario { get; set; }

    public TimeOnly Horario1 { get; set; }

    public virtual ICollection<Funcion> Funciones { get; set; } = new List<Funcion>();

    public virtual ICollection<PromocionesHorario> PromocionesHorarios { get; set; } = new List<PromocionesHorario>();
}