// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPI.Domain.Models;

public partial class Idioma
{
    public int IdIdioma { get; set; }

    public string Idioma1 { get; set; }

    public virtual ICollection<PeliculasIdioma> PeliculasIdiomas { get; set; } = new List<PeliculasIdioma>();
}