// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPI.Domain.Models;

public partial class Marca
{
    public int IdMarca { get; set; }

    public string Marca1 { get; set; }

    public virtual ICollection<ProductosShop> ProductosShops { get; set; } = new List<ProductosShop>();
}