// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CineTPI.Domain.Models;

public partial class Paise
{
    [Key]
    [Column("id_pais")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdPais { get; set; }

    public string Pais { get; set; }

    public virtual ICollection<Pelicula> Peliculas { get; set; } = new List<Pelicula>();

    public virtual ICollection<Provincia> Provincia { get; set; } = new List<Provincia>();
}