// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPI.Domain.Models;

public partial class Pelicula
{
    public int IdPelicula { get; set; }

    public string Titulo { get; set; }

    public string Descripcion { get; set; }

    public DateOnly FechaLanzamiento { get; set; }

    public int? IdPais { get; set; }

    public int? IdFormatoPelicula { get; set; }

    public int? IdClasificacion { get; set; }

    public int? IdDistribuidor { get; set; }

    public int? IdDirector { get; set; }

    public virtual ICollection<Funcion> Funciones { get; set; } = new List<Funcion>();

    public virtual Clasificacione IdClasificacionNavigation { get; set; }

    public virtual Directore IdDirectorNavigation { get; set; }

    public virtual Distribuidore IdDistribuidorNavigation { get; set; }

    public virtual FormatosPelicula IdFormatoPeliculaNavigation { get; set; }

    public virtual Paise IdPaisNavigation { get; set; }

    public virtual ICollection<PeliculasActore> PeliculasActores { get; set; } = new List<PeliculasActore>();

    public virtual ICollection<PeliculasGenero> PeliculasGeneros { get; set; } = new List<PeliculasGenero>();

    public virtual ICollection<PeliculasIdioma> PeliculasIdiomas { get; set; } = new List<PeliculasIdioma>();

    public virtual ICollection<ReseniasPelicula> ReseniasPeliculas { get; set; } = new List<ReseniasPelicula>();
}