// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CineTPI.Domain.Models;

public partial class PeliculasActore
{
    [Key]
    [Column("id_pelicula")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdPeliculaActor { get; set; }

    public int IdPelicula { get; set; }

    public int? IdActor { get; set; }

    public virtual Actore IdActorNavigation { get; set; }

    public virtual Pelicula IdPeliculaNavigation { get; set; }
}