// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CineTPI.Domain.Models;

public partial class PeliculasGenero
{
    [Key]
    [Column("id_pelicula_genero")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdPeliculaGenero { get; set; }

    public int IdPelicula { get; set; }

    public int? IdGenero { get; set; }

    public virtual Genero IdGeneroNavigation { get; set; }

    public virtual Pelicula IdPeliculaNavigation { get; set; }
}