// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPI.Domain.Models;

public partial class PreferenciasCliente
{
    public int IdPreferenciaCliente { get; set; }

    public int CodCliente { get; set; }

    public int IdGenero { get; set; }

    public bool? SuscribeNewsletter { get; set; }

    public virtual Cliente CodClienteNavigation { get; set; }

    public virtual Genero IdGeneroNavigation { get; set; }
}