// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPI.Domain.Models;

public partial class ProductosCombo
{
    public int IdProductoCombo { get; set; }

    public int IdProductoShop { get; set; }

    public int IdCombo { get; set; }

    public decimal PrecioUnitario { get; set; }

    public virtual Combo IdComboNavigation { get; set; }

    public virtual ProductosShop IdProductoShopNavigation { get; set; }
}