// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPI.Domain.Models;

public partial class ProductosShop
{
    public int IdProductoShop { get; set; }

    public string Nombre { get; set; }

    public decimal Precio { get; set; }

    public string Descripcion { get; set; }

    public int Stock { get; set; }

    public int IdMarca { get; set; }

    public int IdTipoProducto { get; set; }

    public virtual ICollection<DetalleFactura> DetalleFacturas { get; set; } = new List<DetalleFactura>();

    public virtual Marca IdMarcaNavigation { get; set; }

    public virtual TiposProducto IdTipoProductoNavigation { get; set; }

    public virtual ICollection<ProductosCombo> ProductosCombos { get; set; } = new List<ProductosCombo>();
}