// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CineTPI.Domain.Models;

public partial class PromocionesFuncione
{
    [Key]
    [Column("id_pelicula")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdPromocionFuncion { get; set; }

    public int IdPromocion { get; set; }

    public int IdFuncion { get; set; }

    public virtual Funcion IdFuncionNavigation { get; set; }

    public virtual Promocione IdPromocionNavigation { get; set; }
}