// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPI.Domain.Models;

public partial class PromocionesFuncione
{
    public int IdPromocionFuncion { get; set; }

    public int IdPromocion { get; set; }

    public int IdFuncion { get; set; }

    public virtual Funcion IdFuncionNavigation { get; set; }

    public virtual Promocione IdPromocionNavigation { get; set; }
}