// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CineTPI.Domain.Models;

public partial class Promocione
{
    [Key]
    [Column("id_pelicula")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdPromocion { get; set; }

    public string Descripcion { get; set; }

    public int IdTipoPromocion { get; set; }

    public int IdEstadoPromocion { get; set; }

    public int IdDiaPromocion { get; set; }

    public int IdFinanciera { get; set; }

    public int IdCanalVenta { get; set; }

    public int? CodCliente { get; set; }

    public virtual Cliente CodClienteNavigation { get; set; }

    public virtual ICollection<DetalleFactura> DetalleFacturas { get; set; } = new List<DetalleFactura>();

    public virtual CanalesVenta IdCanalVentaNavigation { get; set; }

    public virtual DiasPromocione IdDiaPromocionNavigation { get; set; }

    public virtual EstadosPromocione IdEstadoPromocionNavigation { get; set; }

    public virtual Financiera IdFinancieraNavigation { get; set; }

    public virtual TiposPromocione IdTipoPromocionNavigation { get; set; }

    public virtual ICollection<PromocionesFuncione> PromocionesFunciones { get; set; } = new List<PromocionesFuncione>();

    public virtual ICollection<PromocionesHorario> PromocionesHorarios { get; set; } = new List<PromocionesHorario>();
}