// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPI.Domain.Models;

public partial class PromocionesHorario
{
    public int IdPromocionHorario { get; set; }

    public int IdPromocion { get; set; }

    public int IdHorario { get; set; }

    public virtual Horario IdHorarioNavigation { get; set; }

    public virtual Promocione IdPromocionNavigation { get; set; }
}