// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPI.Domain.Models;

public partial class Provincia
{
    public int IdProvincia { get; set; }

    public string Provincia1 { get; set; }

    public int? IdPais { get; set; }

    public virtual ICollection<Ciudade> Ciudades { get; set; } = new List<Ciudade>();

    public virtual Paise IdPaisNavigation { get; set; }
}