// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPI.Domain.Models;

public partial class Puntuacione
{
    public int IdPuntuacion { get; set; }

    public int Puntuacion { get; set; }

    public virtual ICollection<ReseniasPelicula> ReseniasPeliculas { get; set; } = new List<ReseniasPelicula>();
}