// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CineTPI.Domain.Models;

public partial class Reserva
{
    [Key]
    [Column("id_pelicula")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdReserva { get; set; }

    public DateOnly? Fecha { get; set; }

    public int CodCliente { get; set; }

    public int IdEstadoReserva { get; set; }

    public decimal MontoReserva { get; set; }

    public virtual Cliente CodClienteNavigation { get; set; }

    public virtual EstadosReserva IdEstadoReservaNavigation { get; set; }

    public virtual ICollection<ReservaDetalle> ReservaDetalles { get; set; } = new List<ReservaDetalle>();
}