// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CineTPI.Domain.Models;

public partial class ReservaDetalle
{
    [Key]
    [Column("id_reserva_detalle")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdReservaDetalle { get; set; }

    public int IdReserva { get; set; }

    public int IdFuncion { get; set; }

    public int IdButaca { get; set; }

    public virtual Butaca IdButacaNavigation { get; set; }

    public virtual Funcion IdFuncionNavigation { get; set; }

    public virtual Reserva IdReservaNavigation { get; set; }
}