// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPI.Domain.Models;

public partial class ReseniasPelicula
{
    public int IdResenia { get; set; }

    public string Comentario { get; set; }

    public DateTime FechaResenia { get; set; }

    public int IdPelicula { get; set; }

    public int IdPuntuacion { get; set; }

    public int CodCliente { get; set; }

    public virtual Cliente CodClienteNavigation { get; set; }

    public virtual Pelicula IdPeliculaNavigation { get; set; }

    public virtual Puntuacione IdPuntuacionNavigation { get; set; }
}