// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CineTPI.Domain.Models;

public partial class Sala
{
    [Key]
    [Column("id_pelicula")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdSala { get; set; }

    public int? NroSala { get; set; }

    public int? IdTipoSala { get; set; }

    public int? IdSucursal { get; set; }

    public virtual ICollection<Butaca> Butacas { get; set; } = new List<Butaca>();

    public ICollection<Funcion> Funciones { get; set; } = new List<Funcion>();

    public virtual Sucursale IdSucursalNavigation { get; set; }

    public virtual TiposSala IdTipoSalaNavigation { get; set; }
}