// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPI.Domain.Models;

public partial class Sucursale
{
    public int IdSucursal { get; set; }

    public string Nombre { get; set; }

    public int? IdDireccion { get; set; }

    public virtual ICollection<Cajero> Cajeros { get; set; } = new List<Cajero>();

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();

    public virtual Direccione IdDireccionNavigation { get; set; }

    public virtual ICollection<Sala> Salas { get; set; } = new List<Sala>();
}