// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPI.Domain.Models;

public partial class TiposCombo
{
    public int IdTipoCombo { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Combo> Combos { get; set; } = new List<Combo>();
}