// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPI.Domain.Models;

public partial class Turno
{
    public int IdTurno { get; set; }

    public string Turno1 { get; set; }

    public virtual ICollection<Cajero> Cajeros { get; set; } = new List<Cajero>();
}